# Generated by Django 6.0.5 on 2026-07-23 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_categories', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('id_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('driving', 'Driving License'), ('other', 'Other')], default='other', max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('purpose', models.TextField()),
                ('meeting_with', models.CharField(blank=True, max_length=200)),
                ('meeting_with_type', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=15)),
                ('badge_no', models.CharField(blank=True, max_length=10)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=15)),
                ('items_carrying', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='schools.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='visitors.visitorcategory')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_no', models.CharField(max_length=20, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='schools.school')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
