# Generated by Django 6.0.5 on 2026-06-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar_user_first_name_user_last_name_and_more"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="school_id",
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="schools.school",
            ),
        ),
    ]
