# Generated by Django 6.0.5 on 2026-05-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_admission_admission_no'),
        ('students', '0005_teacher_is_active'),
    ]

    operations = [
    ]
