# Generated by Django 6.0.5 on 2026-05-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_classsection_id_alter_teacher_id'),
        ('students', '0006_merge_20260518_1054'),
    ]

    operations = [
    ]
