# Generated by Django 4.0.6 on 2026-05-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_classsection_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('admission_class', 'section', 'year')},
        ),
    ]
