# Generated by Django 6.0.5 on 2026-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_merge_20260519_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], max_length=1),
        ),
    ]
