# Generated by Django 6.0.5 on 2026-05-21 13:21

import django.db.models.deletion
from django.db import migrations, models

def migrate_caste_data(apps, schema_editor):
    Admission = apps.get_model('students', 'Admission')
    Caste = apps.get_model('students', 'Caste')
    for admission in Admission.objects.all():
        if admission.old_caste and admission.old_caste.strip() and admission.old_caste != 'None':
            caste_name = admission.old_caste.strip()
            caste_obj, created = Caste.objects.get_or_create(name=caste_name)
            admission.caste = caste_obj
            admission.save(update_fields=['caste'])

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_admission_gender_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='caste',
            new_name='old_caste',
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='students.caste'),
        ),
        migrations.RunPython(migrate_caste_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='admission',
            name='old_caste',
        ),
    ]
