# Generated by Django 6.0.5 on 2026-05-21 14:18

import django.db.models.deletion
from django.db import migrations, models

def migrate_house_data(apps, schema_editor):
    Admission = apps.get_model('students', 'Admission')
    House = apps.get_model('students', 'House')
    for admission in Admission.objects.all():
        if admission.old_house and admission.old_house.strip() and admission.old_house != 'None':
            house_name = admission.old_house.strip()
            house_obj, created = House.objects.get_or_create(name=house_name)
            admission.house = house_obj
            admission.save(update_fields=['house'])

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_caste_alter_admission_caste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='house',
            new_name='old_house',
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='students.house'),
        ),
        migrations.RunPython(migrate_house_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='admission',
            name='old_house',
        ),
    ]
