# Generated by Django 6.0.5 on 2026-05-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_academicclass_school_id_caste_school_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeInstallmentPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='students.academicclass')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='students.admission')),
            ],
            options={
                'verbose_name': 'Student Fee Installment Payment',
                'verbose_name_plural': 'Student Fee Installment Payments',
                'unique_together': {('admission', 'installment_number')},
            },
        ),
    ]
