# Generated by Django 6.0.5 on 2026-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_student_back_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
