# Generated by Django 6.0.5 on 2026-05-29 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_remove_academic_class_fk_from_fee_installment_and_backdues'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='students.year'),
        ),
        migrations.AddField(
            model_name='category',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='students.year'),
        ),
    ]
