# Generated by Django 6.0.5 on 2026-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_caste_year_category_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
