# Generated by Django 6.0.5 on 2026-05-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_admission_blocked_admission_inactive'),
    ]

    def set_target_type(apps, schema_editor):
        OtherFees = apps.get_model('students', 'OtherFees')
        OtherFees.objects.filter(admission_id__isnull=False).update(target_type='STUDENT')
        OtherFees.objects.filter(admission_id__isnull=True, admission_class_id__isnull=False, section_id__isnull=False).update(target_type='CLASS_SECTION')
        OtherFees.objects.filter(admission_id__isnull=True, admission_class_id__isnull=False, section_id__isnull=True).update(target_type='CLASS')
        OtherFees.objects.filter(admission_id__isnull=True, admission_class_id__isnull=True, year_id__isnull=False).update(target_type='ALL')

    operations = [
        migrations.AddField(
            model_name='otherfees',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All Students'), ('CLASS', 'Class'), ('CLASS_SECTION', 'Class + Section'), ('STUDENT', 'Individual Student')], default='ALL', max_length=20),
        ),
        migrations.RunPython(set_target_type, migrations.RunPython.noop),
    ]
