# Generated by Django 4.0.6 on 2026-05-12 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('admission_no', models.CharField(max_length=100, unique=True)),
                ('pen_no', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('admission_class', models.CharField(blank=True, max_length=100, null=True)),
                ('class_id', models.UUIDField(blank=True, null=True)),
                ('section_id', models.UUIDField(blank=True, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_route_id', models.UUIDField(blank=True, null=True)),
                ('bus_detail_id', models.UUIDField(blank=True, null=True)),
                ('hostel', models.CharField(blank=True, max_length=255, null=True)),
                ('sibling_info', models.TextField(blank=True, null=True)),
                ('student_type', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('is_bpl', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('photo', models.TextField(blank=True, null=True)),
                ('parent_photo', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
