# Generated by Django 4.0.6 on 2026-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='documents',
        ),
        migrations.AddField(
            model_name='admission',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='house',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='ssmid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='tc_document',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/'),
        ),
        migrations.AddField(
            model_name='admission',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='parent_photo',
            field=models.ImageField(blank=True, null=True, upload_to='parents/photos/'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
