# Generated by Django 4.0.6 on 2026-05-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_remove_admission_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='bus_detail_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bus_route_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='section_id',
        ),
        migrations.AddField(
            model_name='admission',
            name='bus_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='bus_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='remarks1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='remarks2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_class',
            field=models.CharField(blank=True, choices=[('NUR', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('PLAY', 'Play Group'), ('I', 'Class 1'), ('II', 'Class 2'), ('III', 'Class 3'), ('IV', 'Class 4'), ('V', 'Class 5'), ('VI', 'Class 6'), ('VII', 'Class 7'), ('VIII', 'Class 8'), ('IX', 'Class 9'), ('X', 'Class 10'), ('XI', 'Class 11'), ('XII', 'Class 12')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
