# Generated by Django 6.0.5 on 2026-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_admission_bus_detail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
