# Generated by Django 4.0.6 on 2026-05-15 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_admission_bus_detail_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(choices=[('NUR', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('PLAY', 'Play Group'), ('I', 'Class 1'), ('II', 'Class 2'), ('III', 'Class 3'), ('IV', 'Class 4'), ('V', 'Class 5'), ('VI', 'Class 6'), ('VII', 'Class 7'), ('VIII', 'Class 8'), ('IX', 'Class 9'), ('X', 'Class 10'), ('XI', 'Class 11'), ('XII', 'Class 12')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], max_length=1)),
            ],
            options={
                'verbose_name': 'Class Section',
                'verbose_name_plural': 'Class Sections',
                'unique_together': {('admission_class', 'section')},
            },
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admission_class',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='section',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='students.classsection')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='students.classsection'),
        ),
    ]
