# Generated by Django 6.0.5 on 2026-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teacher_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
