# Generated by Django 4.0.6 on 2026-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_classsection_id_alter_teacher_id_siblinggroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='year',
            field=models.CharField(blank=True, help_text='Academic year in format YYYY-YYYY', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
