# Generated by Django 6.0.5 on 2026-05-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_merge_20260518_1717'),
        ('students', '0010_merge_20260518_1129'),
    ]

    operations = [
    ]
