# Generated by Django 6.0.5 on 2026-05-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_migrate_category_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
