# Generated by Django 6.0.5 on 2026-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_category_id_alter_fees_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caste',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherfees',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siblinggroup',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
