# Generated by Django 6.0.5 on 2026-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_student_fee_installment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
