# Generated by Django 6.0.5 on 2026-05-28 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_add_driver_to_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBackDues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_dues', to='students.academicclass')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_dues', to='students.admission')),
            ],
            options={
                'verbose_name': 'Student Back Due',
                'verbose_name_plural': 'Student Back Dues',
                'unique_together': {('admission', 'month')},
            },
        ),
    ]
