# Generated by Django 6.0.5 on 2026-05-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_admission_admission_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbackdues',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='studentfeeinstallmentpaid',
            name='academic_class',
        ),
    ]
