# Generated by Django 6.0.5 on 2026-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0035_create_teacher_table"),
        ("students", "0039_revert_admission_id_to_uuid"),
    ]

    operations = []
