# Generated by Django 6.0.5 on 2026-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_merge_20260703_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
