# Generated by Django 6.0.5 on 2026-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
