# Generated by Django 6.0.5 on 2026-06-19 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("established", models.DateField(blank=True, null=True)),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CBSE", "CBSE"),
                            ("ICSE", "ICSE"),
                            ("STATE", "State Board"),
                            ("IB", "IB"),
                            ("CIE", "Cambridge"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("currency_symbol", models.CharField(default="₹", max_length=5)),
                ("academic_start_month", models.PositiveIntegerField(default=4)),
                ("passing_percentage", models.PositiveIntegerField(default=33)),
                ("max_students_per_section", models.PositiveIntegerField(default=40)),
                ("enable_biometric", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("school", "year")},
            },
        ),
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("religious", "Religious"),
                            ("school", "School"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="SchoolNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("fee_receipt", "Fee Receipt"),
                            ("welcome", "Welcome"),
                            ("attendance_alert", "Attendance Alert"),
                            ("exam_result", "Exam Result"),
                            ("general", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "template_type")},
            },
        ),
    ]
